version: 0.2
phases: 
  install:
    # runtime-versions:
    #   nodejs: 18 # or your preferred version
    commands:
      - echo installing serverless...
      - npm install -g serverless
  pre_build:
    commands:
      - echo installing source npm dependencies...
      - npm install
      - echo "Configuring AWS credentials..."
      - export AWS_DEFAULT_REGION=us-east-2
  build:
    commands:
      - echo deployment with serverless framework started
      - sls deploy --stage $ENV_NAME #--region us-east-2
  post_build:
    commands:
      - echo deployment completed!

  artifacts:
    files:
      - '**/*'
