version: 0.2
phases: 
  install:
    commands:
      - echo installing serverless...
      - npm install -g serverless
  pre_build:
    commands:
      - echo installing source npm dependencies...
      - npm install
  build:
    commands:
      - echo deployment with serverless framework started at `date`
      - sls deploy -v -s $ENV_NAME
  post-build:
    commands:
      - echo deployyment completed at `date`!
